name: Deploy container to S3

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: npm install
        working-directory: ./container
      - run: npm run build
        working-directory: ./container
      
      - name: Upload to S3
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME  }}/container/latest
        working-directory: ./container
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
      