name: Deploy container to S3

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
      
      - run: npm install
        working-directory: ./container
      - run: npm run build
        working-directory: ./container